version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  lint-and-test:
    jobs:
      - lint
      - test-and-report

jobs:
  lint:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install --no-install-recommends gcc libev-dev
      - python/install-packages:
          args: isort black flake8 --upgrade
          pkg-manager: pip
          pypi-cache: false
      - run:
          name: Checking imports with isort
          command: isort -q -c --diff .
      - run:
          name: Checking code style with Python Black
          command: black -q --check -t py38 --diff .
      - run:
          name: Checking code standards with Flake8
          command: flake8 .

  test-and-report:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install --no-install-recommends gcc libev-dev
      - run:
          name: Install dependencies
          command: |
            pip install pip tox tox-pip-extensions codecov --upgrade
      - run:
          name: Run tests
          command: tox -e py38
      - run:
          name: Copy report
          command: codecov -t $CODECOV_TOKEN
